# Generated by Django 4.2.19 on 2025-03-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('fname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipcart.flightcategory')),
            ],
        ),
    ]
