# Generated by Django 4.2.19 on 2025-03-09 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0002_flightcategory_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayFlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightnames', models.CharField(max_length=100)),
                ('from_name', models.CharField(max_length=100)),
                ('to_name', models.CharField(max_length=100)),
                ('stime', models.TimeField()),
                ('etime', models.TimeField()),
                ('flightscat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipcart.flightcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='flights',
            name='fname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipcart.todayflights'),
        ),
    ]
