# Generated by Django 4.2.19 on 2025-03-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0004_alter_flights_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='fname',
        ),
        migrations.AddField(
            model_name='flights',
            name='fnames',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flipcart.todayflights'),
        ),
    ]
