# Generated by Django 4.2.19 on 2025-03-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0005_remove_flights_fname_flights_fnames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flights',
        ),
    ]
