# Generated by Django 4.2.19 on 2025-03-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0006_delete_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todayflights',
            name='flightscat',
        ),
        migrations.DeleteModel(
            name='FlightCategory',
        ),
        migrations.DeleteModel(
            name='TodayFlights',
        ),
    ]
