# Generated by Django 4.2.19 on 2025-03-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0008_flight_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight_category',
        ),
    ]
