# Generated by Django 4.2.19 on 2025-03-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0011_ratings_delete_buynow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
