# Generated by Django 4.2.19 on 2025-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0015_rename_product_buynow_products_remove_payment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buynow',
            name='add',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
