# Generated by Django 4.2.19 on 2025-03-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0016_remove_buynow_add_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
