# Generated by Django 4.2.21 on 2025-07-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0020_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
