
services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. gunicorn flipcart_ecom.wsgi:application --chdir flipcart_ecom
    plan: free
