
services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r flipcart_ecom/requirements.txt
    startCommand: PYTHONPATH=. gunicorn flipcart_ecom/flipcart_ecom.wsgi:application
    plan: free
